arm: msm: Fix build
Commit fe9c7cb696 "ARM: fix asm/memory.h build error" caused
missing definitions of PHYS_OFFSET in mach-msm:

arch/arm/include/asm/memory.h:268:42: error: 'PHYS_OFFSET' undeclared \
(first use in this function)  #define PHYS_PFN_OFFSET ((unsigned \
long)(PHYS_OFFSET >> PAGE_SHIFT))  \
arch/arm/include/asm/dma-mapping.h:104:9: note: in expansion of macro \
'PHYS_PFN_OFFSET'  return PHYS_PFN_OFFSET + dma_to_pfn(dev, \
*dev->dma_mask);

An easy workaround is to define PHYS_OFFSET itself,
in the same way we define it for platforms that don't have a private
__virt_to_phys function.

Change-Id: I21af900ae3e5ce51f887a1ab00338a4860be520c